# Generated by Django 6.0.3 on 2026-03-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_apartment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('apartment', models.CharField(max_length=200)),
                ('move_in_date', models.DateField()),
                ('employment_status', models.CharField(max_length=50)),
                ('monthly_income', models.PositiveIntegerField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='applications/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
